parameters:
#    outlandish_twitter_key_words.example.class: Outlandish\TwitterKeyWordsBundle\Example

services:
#    outlandish_twitter_key_words.example:
#        class: %outlandish_twitter_key_words.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
